#!/usr/bin/env bash 
# script to launch MdServ

echo "Please check runtime env first ... "
echo "build and tested env is: "
echo "Ubuntu Linux 4.15.0-38-generic x86_64 or similar os"

echo "command:  uname -srp"
OS_ENV=`uname -srp`
KEY="x86_64"

APP_DIR=`dirname $0`
APP_DIR=`cd "$APP_DIR";pwd`

if echo "$OS_ENV" | grep -q "$KEY"; then
  echo "matched";

  gm_user=$APP_DIR/gm_user.json
  JQ=$APP_DIR/usr/bin/jq
  username=`cat $gm_user | $JQ ".username"`
  password=`cat $gm_user | $JQ ".password"`
  user_id=`curl -s --header "Content-Type: application/json" --request POST  --data "{\"username\": \"$username\", \"password\": \"$password\"}" http://sso.wajinzi.me/api/v3/login/ | $JQ ".user_id"`
  #echo "$user_id"
  if [ "null" = "${user_id// }" ]; then
     echo "Not a valid user, please contact via QQ: 17626852, http://www.myquant.cn"
     exit 0
  fi

  echo "start MdServ ......, you can interrupt it by ctrl+c"
  echo "and you can check log file with 'tail -f logs/opt_log.log'"
else
  echo "runtime not match";
  exit 0
fi

export LD_LIBRARY_PATH=$APP_DIR/usr/lib/:$APP_DIR:$LD_LIBRARY_PATH
export PATH=$APP_DIR/usr/bin:$PATH

if [ ! -f ./setting.json ]; then
  cp $APP_DIR/json/*.json ./
  mkdir -p ./logs
fi

exec "$APP_DIR/usr/bin/mdserv"

